### ISSUE TITLE
invoke webrequest fails

### ISSUE THREAD

**Issue by alexander-entin** [mErlin-sp/mhddos_powershell#2]
The script fails on Windows Server 2012 R2 Standard

Please consider adding this before web requests:
[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"

See
https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel

**Comment by alexander-entin** [comment]
full command that worked:

[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"; $ScriptBlock = [scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/mErlin-sp/mhddos_powershell/master/runner.ps1')); Invoke-Command -ScriptBlock $ScriptBlock -ArgumentList ''

**Comment by mErlin-sp** [comment]
Thank you. Command changed in the last commit.
